/*==============================================================================*/
/* Add App role */
/* Delete App role */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Roles']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add Role']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add Role']")
			.useCss()
			.waitForElementVisible("form input#role-name", DEFAULT_TIMEOUT)
			.customClick("form input#role-name")
			.waitForElementVisible("input#role-name", DEFAULT_TIMEOUT)
			.setValue("input#role-name", "testrole2")
			.waitForElementVisible(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(1) .block-item.ng-scope:nth-child(1) label", DEFAULT_TIMEOUT)
			.customClick(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(1) .block-item.ng-scope:nth-child(1) label")
			.waitForElementVisible("input#com.hermes.communication.mail.send", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.communication.mail.send")
			.waitForElementVisible(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(1) .block-item.ng-scope:nth-child(2) label", DEFAULT_TIMEOUT)
			.customClick(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(1) .block-item.ng-scope:nth-child(2) label")
			.waitForElementVisible("input#com.hermes.communication.mail.read", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.communication.mail.read")
			.waitForElementVisible(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(4) label", DEFAULT_TIMEOUT)
			.customClick(".ui.segment.permissions-editor.ng-scope.ng-isolate-scope .block.ng-scope:nth-child(4) label")
			.waitForElementVisible("input#com.hermes.kibana-ui.kibana", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.kibana-ui.kibana")
			.waitForElementVisible("button:nth-child(2)", DEFAULT_TIMEOUT)
			.customClick("button:nth-child(2)")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Roles']")
			.useCss()
			.waitForElementVisible(".ui.modal.ng-isolate-scope.transition.visible.animating.fade.out .x-btn.x-unselectable.x-box-item.x-toolbar-item.x-btn-default-small.ng-scope:nth-child(2) .x-btn-inner.x-btn-inner-default-small", DEFAULT_TIMEOUT)
			.customClick(".ui.modal.ng-isolate-scope.transition.visible.animating.fade.out .x-btn.x-unselectable.x-box-item.x-toolbar-item.x-btn-default-small.ng-scope:nth-child(2) .x-btn-inner.x-btn-inner-default-small")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(2) .column.ng-scope.ng-isolate-scope.leftAlignedColumn span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(2) .column.ng-scope.ng-isolate-scope.leftAlignedColumn span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Roles']")
			.useCss()
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")

	}
};