/*==============================================================================*/
/* Add client */
/* Add application */
/* Delete client */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add Client']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add Client']")
			.useCss()
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) input", "TestClient")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add Application']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add Application']")
			.useCss()
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) input", "TestApp")
			.waitForElementVisible("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input")
			.waitForElementVisible(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.setValue(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", "55378testg563")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")
			.waitForElementVisible(".lb-main-navigation-item.active span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.active span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Select Client']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Select Client']")
			.useCss()
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) input", "test")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.waitForElementVisible(".x-btn-button.x-btn-button-default-small.x-btn-text.x-btn-button-center", DEFAULT_TIMEOUT)
			.customClick(".x-btn-button.x-btn-button-default-small.x-btn-text.x-btn-button-center")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Select Client']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Select Client']")
			.useCss()
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")

	}
};