/*==============================================================================*/
/* Add user */
/* Assign role and app */
/* Delete user */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span")
			.waitForElementVisible(".main-content", DEFAULT_TIMEOUT)
			.customClick(".main-content")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add User']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add User']")
			.useCss()
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", "ciprian.giurea+testUI@hermes.com")
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", "TestTest")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Edit roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Edit roles']")
			.useCss()
			.waitForElementVisible(".item.ng-scope", DEFAULT_TIMEOUT)
			.customClick(".item.ng-scope")
			.waitForElementVisible("#user-edit-roles .ui.positive.icon.button.ng-scope", DEFAULT_TIMEOUT)
			.customClick("#user-edit-roles .ui.positive.icon.button.ng-scope")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Edit applications']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Edit applications']")
			.useCss()
			.waitForElementVisible(".item.ng-binding.ng-scope", DEFAULT_TIMEOUT)
			.customClick(".item.ng-binding.ng-scope")
			.waitForElementVisible("#user-edit-apps .ui.positive.icon.button.ng-scope", DEFAULT_TIMEOUT)
			.customClick("#user-edit-apps .ui.positive.icon.button.ng-scope")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Back']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Back']")
			.useCss()
			.waitForElementVisible("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .flex-column.flex-row > .flex-column:nth-child(2) > div > input")
			.waitForElementVisible(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", DEFAULT_TIMEOUT)
			.setValue(".flex-column.flex-row > .flex-column:nth-child(2) > div > input", " 2")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Back']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Back']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Users']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Users']")
			.useCss()
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")

	}
};