/*==============================================================================*/
/* Login */
/* launchbase Viewer */
/* Content Management */
/* Add category */
/* Add instance */
/* Delete instance & category */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.waitForElementVisible(".four.wide.column .plus.icon", DEFAULT_TIMEOUT)
			.customClick(".four.wide.column .plus.icon")
			.waitForElementVisible("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input")
			.waitForElementVisible(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.setValue(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", "test")
			.waitForElementVisible("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.customClick("form .ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input")
			.waitForElementVisible(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", DEFAULT_TIMEOUT)
			.setValue(".ui.segment.custom-template.user-edit-template.form > div:nth-child(3) > div > input", "test")
			.waitForElementVisible("form .ui.checkbox input", DEFAULT_TIMEOUT)
			.customClick("form .ui.checkbox input")
			.waitForElementVisible("input[type=submit][value='Apply']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Apply']")
			.waitForElementVisible("input[type=submit][value='Cancel']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Cancel']")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add data property']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add data property']")
			.useCss()
			.waitForElementVisible(".ui.form > .field:nth-child(1) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", DEFAULT_TIMEOUT)
			.customClick(".ui.form > .field:nth-child(1) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified")
			.waitForElementVisible(".ui.form > .field:nth-child(1) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", DEFAULT_TIMEOUT)
			.setValue(".ui.form > .field:nth-child(1) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", "test")
			.waitForElementVisible(".ui.form > .field:nth-child(2) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", DEFAULT_TIMEOUT)
			.customClick(".ui.form > .field:nth-child(2) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified")
			.waitForElementVisible(".ui.form > .field:nth-child(2) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", DEFAULT_TIMEOUT)
			.setValue(".ui.form > .field:nth-child(2) .ng-pristine.ng-untouched.ng-valid.ng-empty.ng-not-modified", "test")
			.waitForElementVisible(".ui.checkbox.checked label", DEFAULT_TIMEOUT)
			.customClick(".ui.checkbox.checked label")
			.waitForElementVisible(".four.wide.column.field:nth-child(3) label", DEFAULT_TIMEOUT)
			.customClick(".four.wide.column.field:nth-child(3) label")
			.waitForElementVisible("button", DEFAULT_TIMEOUT)
			.customClick("button")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='New Instance']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='New Instance']")
			.useCss()
			.waitForElementVisible(".ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-valid-minlength.ng-valid-maxlength.ng-not-modified", DEFAULT_TIMEOUT)
			.customClick(".ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-valid-minlength.ng-valid-maxlength.ng-not-modified")
			.waitForElementVisible(".ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-valid-minlength.ng-valid-maxlength.ng-not-modified", DEFAULT_TIMEOUT)
			.setValue(".ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-valid-minlength.ng-valid-maxlength.ng-not-modified", "test")
			.waitForElementVisible("ng-include:nth-child(3) .ng-scope:nth-child(5) button", DEFAULT_TIMEOUT)
			.customClick("ng-include:nth-child(3) .ng-scope:nth-child(5) button")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='test']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='test']")
			.useCss()
			.waitForElementVisible(".ng-scope.clone .ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-not-modified.md-checked .md-container", DEFAULT_TIMEOUT)
			.customClick(".ng-scope.clone .ng-pristine.ng-untouched.ng-valid.ng-scope.ng-empty.ng-not-modified.md-checked .md-container")
			.waitForElementVisible(".md-button.md-focused", DEFAULT_TIMEOUT)
			.customClick(".md-button.md-focused")
			.waitForElementVisible(".item.ng-scope:nth-child(36) .setting.icon", DEFAULT_TIMEOUT)
			.customClick(".item.ng-scope:nth-child(36) .setting.icon")
			.waitForElementVisible("input[type=submit][value='Cancel']", DEFAULT_TIMEOUT)
			.customClick("input[type=submit][value='Cancel']")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Delete']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Delete']")
			.useCss()

	}
};