/*==============================================================================*/
/* LB navigation trough launchbase Viewer */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.resizeWindow(1872, 902)
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(2) span")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3) span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Back']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Back']")
			.useCss()
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Target Group']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Target Group']")
			.useCss()
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Service Users']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Service Users']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Users']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Users']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Roles']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Roles']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Devices']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Devices']")
			.useCss()
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add .ng-binding", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add .ng-binding")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App Custom Settings']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App Custom Settings']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='App User Properties']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='App User Properties']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Localisations']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Localisations']")
			.useCss()
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.waitForElementVisible(".lb-main-navigation-item.ng-scope.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-scope.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Devices']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Devices']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Sessions']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Sessions']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='In-App']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='In-App']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='A/B Testing']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='A/B Testing']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Campaigns']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Campaigns']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Error']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Error']")
			.useCss()
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")

	}
};