/*==============================================================================*/
/* Add role */
/* Assign role */
/* Delete role */
/*==============================================================================*/

module.exports = {
	'test case': function (client) {
		return client
			.url(`${TEST_RUNNER.CONFIG.baseUrl}/#/login`)
			.waitForElementVisible("form[name=form] input[name='username']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='username']")
			.waitForElementVisible("input[name='username']", DEFAULT_TIMEOUT)
			.setValue("input[name='username']", TEST_RUNNER.CONFIG.username)
			.waitForElementVisible("form[name=form] input[name='password']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[name='password']")
			.waitForElementVisible("input[name='password']", DEFAULT_TIMEOUT)
			.setValue("input[name='password']", TEST_RUNNER.CONFIG.password)
			.waitForElementVisible("form[name=form] input[type=submit][value='Login']", DEFAULT_TIMEOUT)
			.customClick("form[name=form] input[type=submit][value='Login']")
			/* submit form */
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(4) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)")
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(1) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(3)")
			.waitForElementVisible(".lb-main-navigation-item.ng-animate.active-add span", DEFAULT_TIMEOUT)
			.customClick(".lb-main-navigation-item.ng-animate.active-add span")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Roles']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Add Role']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Add Role']")
			.useCss()
			.waitForElementVisible("form input#role-name", DEFAULT_TIMEOUT)
			.customClick("form input#role-name")
			.waitForElementVisible("input#role-name", DEFAULT_TIMEOUT)
			.setValue("input#role-name", "testRole")
			.waitForElementVisible("input#com.hermes.communication.mail.send", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.communication.mail.send")
			.waitForElementVisible("input#com.hermes.communication.mail.read", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.communication.mail.read")
			.waitForElementVisible("input#com.hermes.cloud9.cloud9", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.cloud9.cloud9")
			.waitForElementVisible("input#com.hermes.core.device.read", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.device.read")
			.waitForElementVisible("input#com.hermes.core.device.write", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.device.write")
			.waitForElementVisible("input#com.hermes.core.application.read", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.application.read")
			.waitForElementVisible("input#com.hermes.core.application.write", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.application.write")
			.waitForElementVisible("input#com.hermes.core.application.settings", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.application.settings")
			.waitForElementVisible("input#com.hermes.core.application.customSettings", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.application.customSettings")
			.waitForElementVisible("input#com.hermes.core.application.localization", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.application.localization")
			.waitForElementVisible("input#com.hermes.core.client.settings", DEFAULT_TIMEOUT)
			.customClick("input#com.hermes.core.client.settings")
			.waitForElementVisible("button:nth-child(2)", DEFAULT_TIMEOUT)
			.customClick("button:nth-child(2)")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Back']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Back']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Users']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Users']")
			.useCss()
			.waitForElementVisible(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(3) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(5)", DEFAULT_TIMEOUT)
			.customClick(".mdtTable.md-whiteframe-z1._md.layout-column ng-include .tbodyTrRow.ng-scope:nth-child(3) .column.ng-scope.ng-isolate-scope.leftAlignedColumn:nth-child(5)")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Edit roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Edit roles']")
			.useCss()
			.waitForElementVisible(".item.ng-scope", DEFAULT_TIMEOUT)
			.customClick(".item.ng-scope")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Back']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Back']")
			.useCss()
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Roles']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Roles']")
			.useCss()
			.waitForElementVisible(".x-btn-inner.x-btn-inner-default-small.ng-binding", DEFAULT_TIMEOUT)
			.customClick(".x-btn-inner.x-btn-inner-default-small.ng-binding")
			.useXpath()
			.waitForElementVisible("//a[normalize-space(text())='Users']", DEFAULT_TIMEOUT)
			.customClick("//a[normalize-space(text())='Users']")
			.useCss()

	}
};